<?php

/**
 * sfOauthServerConsumerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfOauthServerConsumerTable extends PluginsfOauthServerConsumerTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfOauthServerConsumerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfOauthServerConsumer');
    }
}