<?php

/**
 * sfOauthServerNonceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfOauthServerNonceTable extends PluginsfOauthServerNonceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfOauthServerNonceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfOauthServerNonce');
    }
}