<?php

/**
 * sfOauthServerUserScopeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfOauthServerUserScopeTable extends PluginsfOauthServerUserScopeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfOauthServerUserScopeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfOauthServerUserScope');
    }
}