<?php

/**
 * BasesfOauthServerNonce
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nonce
 * 
 * @method string             getNonce() Returns the current record's "nonce" value
 * @method sfOauthServerNonce setNonce() Sets the current record's "nonce" value
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfOauthServerNonce extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_oauth_server_nonce');
        $this->hasColumn('nonce', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 40,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}