<?php

/**
 * EntradaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntradaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntradaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Entrada');
    }
}