<?php

/**
 * UsuariTeAssignaturesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuariTeAssignaturesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuariTeAssignaturesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuariTeAssignatures');
    }
}