<?php

/**
 * UsuariEspiaUsuariTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuariEspiaUsuariTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuariEspiaUsuariTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuariEspiaUsuari');
    }
}