<?php

/**
 * BaseContingutTeOpcio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $contingut_id
 * @property integer $opcio_id
 * @property Contingut $Contingut
 * @property Opcio $Opcio
 * 
 * @method integer          getContingutId()  Returns the current record's "contingut_id" value
 * @method integer          getOpcioId()      Returns the current record's "opcio_id" value
 * @method Contingut        getContingut()    Returns the current record's "Contingut" value
 * @method Opcio            getOpcio()        Returns the current record's "Opcio" value
 * @method ContingutTeOpcio setContingutId()  Sets the current record's "contingut_id" value
 * @method ContingutTeOpcio setOpcioId()      Sets the current record's "opcio_id" value
 * @method ContingutTeOpcio setContingut()    Sets the current record's "Contingut" value
 * @method ContingutTeOpcio setOpcio()        Sets the current record's "Opcio" value
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContingutTeOpcio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contingut_te_opcio');
        $this->hasColumn('contingut_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('opcio_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contingut', array(
             'local' => 'contingut_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Opcio', array(
             'local' => 'opcio_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}