<?php

/**
 * BaseContingut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $action_part
 * @property string $view_part
 * @property boolean $es_contingut
 * @property Doctrine_Collection $ContingutTeOpcions
 * 
 * @method string              getNom()                Returns the current record's "nom" value
 * @method string              getActionPart()         Returns the current record's "action_part" value
 * @method string              getViewPart()           Returns the current record's "view_part" value
 * @method boolean             getEsContingut()        Returns the current record's "es_contingut" value
 * @method Doctrine_Collection getContingutTeOpcions() Returns the current record's "ContingutTeOpcions" collection
 * @method Contingut           setNom()                Sets the current record's "nom" value
 * @method Contingut           setActionPart()         Sets the current record's "action_part" value
 * @method Contingut           setViewPart()           Sets the current record's "view_part" value
 * @method Contingut           setEsContingut()        Sets the current record's "es_contingut" value
 * @method Contingut           setContingutTeOpcions() Sets the current record's "ContingutTeOpcions" collection
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContingut extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contingut');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('action_part', 'string', 700, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 700,
             ));
        $this->hasColumn('view_part', 'string', 700, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 700,
             ));
        $this->hasColumn('es_contingut', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ContingutTeOpcio as ContingutTeOpcions', array(
             'local' => 'id',
             'foreign' => 'contingut_id'));
    }
}