<?php

/**
 * BaseOpcio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $module
 * @property string $action
 * @property Doctrine_Collection $ContingutTeOpcions
 * 
 * @method string              getNom()                Returns the current record's "nom" value
 * @method string              getModule()             Returns the current record's "module" value
 * @method string              getAction()             Returns the current record's "action" value
 * @method Doctrine_Collection getContingutTeOpcions() Returns the current record's "ContingutTeOpcions" collection
 * @method Opcio               setNom()                Sets the current record's "nom" value
 * @method Opcio               setModule()             Sets the current record's "module" value
 * @method Opcio               setAction()             Sets the current record's "action" value
 * @method Opcio               setContingutTeOpcions() Sets the current record's "ContingutTeOpcions" collection
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOpcio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('opcio');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('module', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('action', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ContingutTeOpcio as ContingutTeOpcions', array(
             'local' => 'id',
             'foreign' => 'opcio_id'));
    }
}