<?php

/**
 * BaseSessio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $data_hora_inici
 * @property timestamp $data_hora_fi
 * @property integer $assignatura_id
 * @property string $aula
 * @property string $tipus
 * @property string $grup_seminari
 * @property string $grup_practiques
 * @property string $grup_teoria
 * @property Assignatura $Assignatura
 * 
 * @method timestamp   getDataHoraInici()   Returns the current record's "data_hora_inici" value
 * @method timestamp   getDataHoraFi()      Returns the current record's "data_hora_fi" value
 * @method integer     getAssignaturaId()   Returns the current record's "assignatura_id" value
 * @method string      getAula()            Returns the current record's "aula" value
 * @method string      getTipus()           Returns the current record's "tipus" value
 * @method string      getGrupSeminari()    Returns the current record's "grup_seminari" value
 * @method string      getGrupPractiques()  Returns the current record's "grup_practiques" value
 * @method string      getGrupTeoria()      Returns the current record's "grup_teoria" value
 * @method Assignatura getAssignatura()     Returns the current record's "Assignatura" value
 * @method Sessio      setDataHoraInici()   Sets the current record's "data_hora_inici" value
 * @method Sessio      setDataHoraFi()      Sets the current record's "data_hora_fi" value
 * @method Sessio      setAssignaturaId()   Sets the current record's "assignatura_id" value
 * @method Sessio      setAula()            Sets the current record's "aula" value
 * @method Sessio      setTipus()           Sets the current record's "tipus" value
 * @method Sessio      setGrupSeminari()    Sets the current record's "grup_seminari" value
 * @method Sessio      setGrupPractiques()  Sets the current record's "grup_practiques" value
 * @method Sessio      setGrupTeoria()      Sets the current record's "grup_teoria" value
 * @method Sessio      setAssignatura()     Sets the current record's "Assignatura" value
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSessio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sessio');
        $this->hasColumn('data_hora_inici', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('data_hora_fi', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('assignatura_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('aula', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tipus', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('grup_seminari', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('grup_practiques', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('grup_teoria', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Assignatura', array(
             'local' => 'assignatura_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}