<?php

/**
 * sfOauthServerRequestTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfOauthServerRequestTokenTable extends PluginsfOauthServerRequestTokenTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfOauthServerRequestTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfOauthServerRequestToken');
    }
}