<?php

/**
 * sfOauthServerAccessTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfOauthServerAccessTokenTable extends PluginsfOauthServerAccessTokenTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfOauthServerAccessTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfOauthServerAccessToken');
    }
}