<?php

/**
 * sfOauthServerDeveloperTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfOauthServerDeveloperTable extends PluginsfOauthServerDeveloperTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfOauthServerDeveloperTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfOauthServerDeveloper');
    }
}