<?php

/**
 * OpcioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpcioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpcioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Opcio');
    }
}