<?php

/**
 * BaseContingut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $text
 * @property Doctrine_Collection $Entrades
 * @property Doctrine_Collection $ContingutTeOpcions
 * 
 * @method string              getNom()                Returns the current record's "nom" value
 * @method string              getText()               Returns the current record's "text" value
 * @method Doctrine_Collection getEntrades()           Returns the current record's "Entrades" collection
 * @method Doctrine_Collection getContingutTeOpcions() Returns the current record's "ContingutTeOpcions" collection
 * @method Contingut           setNom()                Sets the current record's "nom" value
 * @method Contingut           setText()               Sets the current record's "text" value
 * @method Contingut           setEntrades()           Sets the current record's "Entrades" collection
 * @method Contingut           setContingutTeOpcions() Sets the current record's "ContingutTeOpcions" collection
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContingut extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contingut');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('text', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Entrada as Entrades', array(
             'local' => 'id',
             'foreign' => 'contingut_id'));

        $this->hasMany('ContingutTeOpcio as ContingutTeOpcions', array(
             'local' => 'id',
             'foreign' => 'contingut_id'));
    }
}