<?php

/**
 * BaseCarreraCursTeAssignatura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $carrera_curs_id
 * @property integer $assignatura_id
 * @property CarreraCurs $CarreraCurs
 * @property Assignatura $Assignatura
 * 
 * @method integer                  getCarreraCursId()   Returns the current record's "carrera_curs_id" value
 * @method integer                  getAssignaturaId()   Returns the current record's "assignatura_id" value
 * @method CarreraCurs              getCarreraCurs()     Returns the current record's "CarreraCurs" value
 * @method Assignatura              getAssignatura()     Returns the current record's "Assignatura" value
 * @method CarreraCursTeAssignatura setCarreraCursId()   Sets the current record's "carrera_curs_id" value
 * @method CarreraCursTeAssignatura setAssignaturaId()   Sets the current record's "assignatura_id" value
 * @method CarreraCursTeAssignatura setCarreraCurs()     Sets the current record's "CarreraCurs" value
 * @method CarreraCursTeAssignatura setAssignatura()     Sets the current record's "Assignatura" value
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarreraCursTeAssignatura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('carrera_curs_te_assignatura');
        $this->hasColumn('carrera_curs_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('assignatura_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarreraCurs', array(
             'local' => 'carrera_curs_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Assignatura', array(
             'local' => 'assignatura_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}