<?php

/**
 * BaseUsuariEspiaUsuari
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuari_base
 * @property integer $usuari_objectiu
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer           getUsuariBase()      Returns the current record's "usuari_base" value
 * @method integer           getUsuariObjectiu()  Returns the current record's "usuari_objectiu" value
 * @method sfGuardUser       getSfGuardUser()     Returns the current record's "sfGuardUser" value
 * @method UsuariEspiaUsuari setUsuariBase()      Sets the current record's "usuari_base" value
 * @method UsuariEspiaUsuari setUsuariObjectiu()  Sets the current record's "usuari_objectiu" value
 * @method UsuariEspiaUsuari setSfGuardUser()     Sets the current record's "sfGuardUser" value
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuariEspiaUsuari extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuari_espia_usuari');
        $this->hasColumn('usuari_base', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('usuari_objectiu', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'usuari_objectiu',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}