<?php

/**
 * BaseUsuariTeAssignatures
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuari_id
 * @property integer $assignatura_id
 * @property Assignatura $Assignatura
 * 
 * @method integer              getUsuariId()       Returns the current record's "usuari_id" value
 * @method integer              getAssignaturaId()  Returns the current record's "assignatura_id" value
 * @method Assignatura          getAssignatura()    Returns the current record's "Assignatura" value
 * @method UsuariTeAssignatures setUsuariId()       Sets the current record's "usuari_id" value
 * @method UsuariTeAssignatures setAssignaturaId()  Sets the current record's "assignatura_id" value
 * @method UsuariTeAssignatures setAssignatura()    Sets the current record's "Assignatura" value
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuariTeAssignatures extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuari_te_assignatures');
        $this->hasColumn('usuari_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('assignatura_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Assignatura', array(
             'local' => 'assignatura_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}