<?php

/**
 * BaseAssignatura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property Doctrine_Collection $Sessions
 * @property Doctrine_Collection $UsuariTeAssignatures
 * @property Doctrine_Collection $CarreraCursTeAssignatures
 * 
 * @method string              getNom()                       Returns the current record's "nom" value
 * @method Doctrine_Collection getSessions()                  Returns the current record's "Sessions" collection
 * @method Doctrine_Collection getUsuariTeAssignatures()      Returns the current record's "UsuariTeAssignatures" collection
 * @method Doctrine_Collection getCarreraCursTeAssignatures() Returns the current record's "CarreraCursTeAssignatures" collection
 * @method Assignatura         setNom()                       Sets the current record's "nom" value
 * @method Assignatura         setSessions()                  Sets the current record's "Sessions" collection
 * @method Assignatura         setUsuariTeAssignatures()      Sets the current record's "UsuariTeAssignatures" collection
 * @method Assignatura         setCarreraCursTeAssignatures() Sets the current record's "CarreraCursTeAssignatures" collection
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssignatura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('assignatura');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Sessio as Sessions', array(
             'local' => 'id',
             'foreign' => 'assignatura_id'));

        $this->hasMany('UsuariTeAssignatura as UsuariTeAssignatures', array(
             'local' => 'id',
             'foreign' => 'assignatura_id'));

        $this->hasMany('CarreraCursTeAssignatura as CarreraCursTeAssignatures', array(
             'local' => 'id',
             'foreign' => 'assignatura_id'));
    }
}