<?php

/**
 * BaseCarreraCurs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $url_horari
 * @property Doctrine_Collection $Assignatures
 * 
 * @method string              getNom()          Returns the current record's "nom" value
 * @method string              getUrlHorari()    Returns the current record's "url_horari" value
 * @method Doctrine_Collection getAssignatures() Returns the current record's "Assignatures" collection
 * @method CarreraCurs         setNom()          Sets the current record's "nom" value
 * @method CarreraCurs         setUrlHorari()    Sets the current record's "url_horari" value
 * @method CarreraCurs         setAssignatures() Sets the current record's "Assignatures" collection
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarreraCurs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('carrera_curs');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('url_horari', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Assignatura as Assignatures', array(
             'local' => 'id',
             'foreign' => 'carrera_curs_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}