<?php

/**
 * BaseEntrada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $contingut_id
 * @property string $nom
 * @property integer $longitud
 * @property integer $amplada
 * @property Contingut $Contingut
 * 
 * @method integer   getContingutId()  Returns the current record's "contingut_id" value
 * @method string    getNom()          Returns the current record's "nom" value
 * @method integer   getLongitud()     Returns the current record's "longitud" value
 * @method integer   getAmplada()      Returns the current record's "amplada" value
 * @method Contingut getContingut()    Returns the current record's "Contingut" value
 * @method Entrada   setContingutId()  Sets the current record's "contingut_id" value
 * @method Entrada   setNom()          Sets the current record's "nom" value
 * @method Entrada   setLongitud()     Sets the current record's "longitud" value
 * @method Entrada   setAmplada()      Sets the current record's "amplada" value
 * @method Entrada   setContingut()    Sets the current record's "Contingut" value
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntrada extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entrada');
        $this->hasColumn('contingut_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('longitud', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('amplada', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contingut', array(
             'local' => 'contingut_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}