<?php

/**
 * AssignaturaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssignaturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssignaturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Assignatura');
    }
}