<?php

/**
 * ContingutTeOpcioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContingutTeOpcioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContingutTeOpcioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContingutTeOpcio');
    }
}