<?php

/**
 * CarreraCursTeAssignaturaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarreraCursTeAssignaturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarreraCursTeAssignaturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CarreraCursTeAssignatura');
    }
}