<?php

/**
 * Sessio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ttupf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Sessio extends BaseSessio
{
	public function isGroupSet() {
		if($this->getGrupPractiques() ||
			$this->getGrupTeoria() ||
			$this->getGrupSeminari()) {
			return true;
		}
		else {
			return false;
		}
	} 
	
	public function isAulaSet() {
		if($this->getAula()) {
			return true;
		}
		else {
			return false;
		}
	}

	public function isTypeSet() {
		if($this->getTipus()) {
			return true;
		}
		else {
			return false;
		}
	}
	
	public function isAssignaturaSet() {
		if($this->getAssignatura()) {
			return true;
		}
		else {
			return false;
		}
	}
	
	public function isDateTimeSet() {
		if($this->getDataHoraInici() ||
			$this->getDataHoraFi())  {
			return true;
		}
		else {
			return false;
		}
	}
}
