<?php

/**
 * ContingutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContingutTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContingutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contingut');
    }
}