<?php

/**
 * UsuariTeAssignaturaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuariTeAssignaturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuariTeAssignaturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuariTeAssignatura');
    }
}